name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
        
      - name: Checkout Source Repository (Jenkins_proj)
        uses: actions/checkout@v4
        with:
          repository: Deeps-22/Jenkins_proj
          path: source-repo
          
      - name: Checkout Target Repository (Portfolio)
        uses: actions/checkout@v4
        with:
          repository: Deeps-22/portfolio
          path: target-repo

      - name: Copy Files
        run: |
          cp -r source-repo/* target-repo
          cd target-repo
          git config --global user.name ""
          git config --global user.email "" 
          git add .
          git commit -m "Copied files from Jenkins_proj"
          git push

      - name: after copy
        run:  ls


